apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
    <head><title>Welcome to ArgoCD Web!</title></head>
    <body>
      <h1>🚀 ArgoCD Auto Sync Test Success! 🎉</h1>
      <p>Nội dung này được cập nhật tự động khi có thay đổi trên GitHub!</p>
    </body>
    </html>
