apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="vi">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Website Tĩnh với ArgoCD</title>
    </head>
    <body>
        <h1>🚀 Chào mừng bạn với website tĩnh!</h1>
        <p>Nội dung này được deploy qua Kubernetes và ArgoCD.</p>
    </body>
    </html>
